project:
  type: website
  output-dir: docs
  preview:
    port: 3333

website:
  title: "Unveiling the Dynamics of Pedestrian Movement in Center City, Philadelphia"
  site-url: "https://XiayuanshanGao_Final/quarto-website-template" 
  repo-actions: [source]


  sidebar:
    logo: "images/course-icon.png"
    pinned: true
    align: center       

    style: "docked"
    search: true
    collapse-level: 2
    contents:
          - analysis/Final.ipynb

format:
  html:
    highlight-style: solarized
    theme: cosmo
    css: styles.css
    code-copy: true
    code-overflow: wrap
    toc: true




